#!/usr/bin/env python3

from collections import defaultdict


def ClumpFinding(genome: str, k: int, L: int, t: int) -> list:
    """
    Finds all distinct k-mers forming (L, t)-clumps in a genome.

    Args:
        genome (str): The input DNA sequence.
        k (int): Length of k-mers.
        L (int): Length of the window to search within.
        t (int): Minimum number of occurrences for a k-mer to form a clump.

    Returns:
        list: List of distinct k-mers forming clumps.
    """
    with open(genome, "r") as file:
        genome= file.read().strip()
    # genome = genome.upper().strip()
    n = len(genome)
    # kmer_positions = defaultdict(list)
    clump_kmers = set()

    # Sliding window over the genome
    for i in range(n - L + 1):
        # Extract the current window
        window = genome[i : i + L]
        freq = defaultdict(int)

        # Count k-mers in the window
        for j in range(L - k + 1):
            kmer = window[j : j + k]
            freq[kmer] += 1

        # Check for clumps
        for kmer, count in freq.items():
            if count >= t:
                clump_kmers.add(kmer)

    return sorted(clump_kmers)



# # genome = "TCATGGCCCCCCGTGCTTGTACAACCTCGTATTAGATAGTGCCGTTCTCACTCACTCGGTCGACGCGTTGTATAGAGTATAGCACCAAAGTGTTTGGGACACTGTGGAACTGTGGAAACTGGCCGTACACTGTGGAGATAACACTGTGGAGGACTAATCTTCGAACACTGTGGACTGTGGATTCGTCGAAGAGCATACCTAAGACGTCCGCACATTCAAGGCTGTCAACCTAGGACGTAGGAAATTTAGAAAGCTCAGTATACGTCATGTGTACGGCCCCACTGATTACACCGAGACATTGTATAGATGGGTGGTGGGAATGTCGCGAAAGGACAGATATGGCTAAATCTGAACCATCTAAACCATTAAACCATTATGGTCCACGACATCTAAACCATTATTATTACTACTATATCTTTTGTGAAAACCATTATAAAACCATTATTATACTGGCCATCACCAGTGCTGGAGAGGTTTCGGGTAACTAGTACCACGCAGCCCCTGGATTAACAACTTCCCCTGGATTACAGGCAGGAAATGTTTAGGCCCCTGGATTACCCTGGATTAGGATTAAATTTACTCCCTGGATTAGTAACCTCAGTGGGGTTTGGTCACACACTTAGTACTTATTTCTAGAATGAGCGCCTACGTGACCGCGCAACCCTAAGTGGTCACATTTGCACATTCAGAAAGTCACCGTGCCCTTATAGTCACCGTGACATAGTCACCGTGATTCTGAAACTATGGACAAACTTTCGTATGAGTCAGTCACCAGTCACCGTGGTGTGTATCTTGCCTATCGTGTGCAGGATAATGTGGTAGGTACTGAGAAATAGTATGGCTATAGTATGCTTAGGCGTGGCGTGGCGGTACTGAGAAAGAGTACTGAGAAATGAGAAAAACAGATACTGAGAAAGCATAATGATAAAAACCGCCTGTGGGGATTAATATGTGGGGATTAGGGGATGTGGGGGTGGGGATTAAGCGCTCCTGATAGTAGACCTCAAGTGGGGATTAGAGTTTGGGTAGTAGGCCTTAACGACCTAACGACCTCGGACCTCGAAGTCTAAACGACCTCGCCTCGGTATCAAAAACAACGACCTCGCAGAATGGTTCTCGATACCCGACACTAAACCGGGTACGGGACAATAAAGCTAAAATTCTACTTCCACACCTCGGCACTATAGCAGACCTCAAGGGTGTTTCACCTCGGCAGGCAAACACCTCGGCAATAACCATTGGCTTTCAGCTTTCAGCTGCAGCGGCTTTCAGCTGCTAGCTTTTCAGCTTTCACCTATCGCTTTCAGCTCCTATCTCTTCACCGCTTTCAGCTTCACCTATGGATTCGCGGGAACCCTTCAAAAAGGGAGGATTCGGCAAAGATGGAGGATTCGAGGATTCGCCATGTCTTTCTCTACCAGTCCGTAACTCTACCAGTCCAGTCATTCCTACCAGTCCCTACCAGTCCCCTACCAGTCCTACCAGTCCATGAAGCTTCTACCAGTCCTACCATTGCGAGCGTTACATCTACTAACGCACACCATCACGGGTCAGTGTTTGCCGTAACGAAAAGTTTCGACTCCCTACAAAGGGGCATATTGTCCGGGGAGGTGATGTCGGATCTTATTCTTGCCAACCTTCACCCGGTGCCACCCGGTGCTTAATACTTTCTCACCCGGTGCGCACACCCGGTGCCCACCCGGTGCGCCCCATACCCAAAGTTAACACCCGGTGCCAAAGTTACCCAAAGTTATCCCAAAGTTACGAGCTGGCCCAAAGTTATTACCGGGTCGGGTAGGCCCAAAGTTAAGCCCGCACATTCATTAATGGCGGAGTTGGGGGCAGACTATCGGCCGTCACATTAATGGCCATTAATGCATTAATGGCGTTAGCTCCATTATTGGTCGAAATACCCGAGCTCGGGGCGGGGGCGCGCGCGGGGGCGCGCGGCGGGGGCGCGCGGGGGCGCGTGTGCTAGGTGGGCTTCTTAAAAGTAGTAT"
# # k = 10
# # L = 100
# # t = 4

genome = "datasets/Salmonella_full_genome.txt"
k = 9
L = 500
t = 3

result = ClumpFinding(genome, k, L, t)
print("Clump k-mers:", " ".join(result))



